### ISSUE TITLE
openjdk11@11.0.2-9: download via aria2 failed

### ISSUE THREAD

**Issue by aaaweisen** [se35710/scoop-java#52] opened 2019-04-28 06:27 UTC

**Comment by se35710** [comment] 2019-04-28 10:32
Duplicate of #51

**Closed** 2019-04-29 19:12 UTC
Labels: duplicate

**Comment by se35710** [comment] 2019-04-29 19:14
BTW, you should not use openjdk11 unless needed to. There are no new builds published at jdk.java.net for Java 11. Select one of the other OpenJDK distributions, for example AdoptOpenJDK.
