### ISSUE TITLE
openjdk@12.0.1-12: download via aria2 failed

### ISSUE THREAD

**Issue by aaaweisen** [se35710/scoop-java#53] opened 2019-04-28 10:04 UTC
ERROR Download failed! (Error 1) An unknown error occurred
ERROR https://download.java.net/java/GA/jdk12.0.1/69cfe15208a647278a19ef0990eea691/12/GPL/openjdk-12.0.1_windows-x64_bin.zip
    referer=https://download.java.net/java/GA/jdk12.0.1/69cfe15208a647278a19ef0990eea691/12/GPL/
    dir=C:\Users\daojia\scoop\cache
    out=openjdk#12.0.1-12#https_download.java.net_java_GA_jdk12.0.1_69cfe15208a647278a19ef0990eea691_12_GPL_openjdk-12.0.1_windows-x64_bin.zip

ERROR & 'C:\Users\daojia\scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Users\daojia\scoop\cache\openjdk.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --ret
ry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=48264 --continue

Please try again or create a new issue by using the following link and paste your console output:

**Comment by se35710** [comment] 2019-04-28 10:33
Duplicate of #51

**Closed** 2019-04-29 19:12 UTC
Labels: duplicate
